Update guzzle dependency to 7.0
esolitos/pwnedpasswords pull request #2
Opened 2023-05-11 10:54 UTC by nicrodgers

2023-05-11 19:05 UTC, esolitos requested changes
Hi, thank you for the PR, very much appreciated!
A small change: I'd suggest to keep the 6.x backward compatibility. :)

2023-05-11 19:05 UTC, esolitos commented on composer.json
> +        "guzzlehttp/guzzle": "^7.0"
```suggestion
        "guzzlehttp/guzzle": "^6.2 || ^7.0"
```

2023-05-11 19:40 UTC, nicrodgers commented
Very good point, done :)

2023-05-12 10:29 UTC, esolitos approved these changes

2023-05-12 10:30 UTC, merged